### PR TITLE
Reworking of the MDCF Architect documentation

### PR DESCRIPTION
**Pull request by scbarrett**
Framework for describing the entire tool chain -- two out of three completed. Please review.

Includes xdml.jar, which will be removed once a better location has been secured.

@sprocter @yjkim78

### CODE REVIEW

**Comment by rvprasad** [comment]
Where is the documentation posted on the web?

**Comment by sprocter** [comment]
@rvprasad the documentation is online at http://santoslab.org/pub/mdcf-architect/

**Comment by rvprasad** [comment]
@sprocter I am asking for the location of documentation that needs to be reviewed by @scbarrett.  Is this the same as the one at santoslab.org/pub?  If so, what are the changes that needs to be reviewed for @scbarrett?

**Comment by scbarrett** [comment]
The original is here: http://santoslab.org/pub/mdcf-architect/

The new stuff is in a fork that is pending review:
https://github.com/scbarrett/aadl-translator/tree/master/mdcf-architect-documentation

You have to build it to see it, or I can send you a zip of the HTML.

**Comment by rvprasad** [comment]
I suggest hosting it in your personal web space or somewhere under
santoslab/pub.

Venkatesh-Prasad Ranganath
http://about.me/rvprasad

**Comment by scbarrett** [comment]
Pull from request #29 instead.

**Pull request closed without merging**
